version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 50051:50051
    command: air -c .air.toml -d
    volumes:
      - .:/dev/app:cached